services:
  - type: web
    name: stuv-loe-internal-cms
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt
    buildCommand: yarn install && yarn build
    healthCheckPath: /_health
    disk:
      name: stuv-loe-internal-cms-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 20.13
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        fromDatabase:
          name: stuv-loe-internal-cms
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: stuv-loe-internal-cms
    plan: starter
